import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TIC_TAC_TOE } from "./const";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: TIC_TAC_TOE,
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
