import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { HEADER_CLASS, TIC_TAC_TOE } from "./const";

import PlayWithFriendBtn from "@/components/section/header/play-with-friend-btn";
import TitleHeader from "@/components/section/header/title";
import { ThemeModeToggle } from "@/components/theme-mode-toggle";
import { ThemeProvider } from "@/components/theme-provider";
import { AnimatedTooltip } from "@/components/ui/animated-tooltip";
import { DotBackground } from "@/components/ui/dot-grid-pattern";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: TIC_TAC_TOE,
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(inter.className, "select-none min-h-screen font-sans")}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="z-10 w-full m-auto max-w-5xl flex items-center justify-between lg:pt-12 lg:px-16 lg:pb-8 lg:flex ">
            <div className={HEADER_CLASS}>
              <TitleHeader />
            </div>

            <div className="z-20 fixed bottom-0 left-0 flex w-full items-center justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black  lg:static lg:size-auto lg:bg-none">
              <div className="flex justify-between items-center gap-3  mb-8 lg:mb-0 pt-5 pb-1 lg:p-0">
                <PlayWithFriendBtn />
                <ThemeModeToggle />
                <div className=" flex place-items-center gap-2 p-0">
                  By,
                  <AnimatedTooltip
                    item={{
                      id: 1,
                      name: "Satyendrasinh Chauhan",
                      designation: "Frontend Developer",
                      image: "/github.svg",
                      blurDataURL: "/github-blur.png",
                    }}
                  />
                </div>
              </div>
            </div>
          </header>

          <main className="flex flex-col items-center space-y-5 mt-5 lg:mt-0 overflow-hidden ">
            {children}
          </main>
        </ThemeProvider>
        <DotBackground />
      </body>
    </html>
  );
}
